### ISSUE TITLE
compile error with http-media-0.7 and base-4.6

### ISSUE THREAD

**Issue by hvr** [zmthy/http-media#22]
```
Configuring component lib from http-media-0.7.0...
Preprocessing library http-media-0.7.0...

src/Network/HTTP/Media.hs:61:18:
    Could not find module `Data.Proxy'
```

I've already revised the meta-data at https://hackage.haskell.org/package/http-media-0.7.0/revisions/ so there's no immediate need to upload a new release (unless for restoring base-4.6 support).

See also https://matrix.hackage.haskell.org/package/http-media for an overview

PS: While at it, I also corrected the meta-data for

 - https://hackage.haskell.org/package/http-media-0.6.0/revisions
 - https://hackage.haskell.org/package/http-media-0.5.1/revisions
 - https://hackage.haskell.org/package/http-media-0.5.0/revisions

which required a tighter upper bound on `base` due to the Foldable/Traversable incompat

**Comment by zmthy** [comment]
Thanks. I should probably tighten the upper bound on `base` in the latest version as well.

**Comment by zmthy** [comment]
Ah, looks like I did think to raise the lower bound when we dropped support for 4.6, but I accidentally only raised it on the test suite.

I've tightened the bounds on the develop branch. I'm going to mark this as closed because you've fixed the problem for existing versions and the problem will be solved for releases going forward. Thanks for your help.
