### ISSUE TITLE
Allow deconstructing Quality values

### ISSUE THREAD

**Issue by iand675** [zmthy/http-media#26]
I've got a use case in which I want to see what the priorities are for the different content types. Unfortunately, there doesn't seem to be a way to get at the information through the Quality type... looking at the datatype, it doesn't seem too risky to provide a way to enable accessing the data after the fact via some sort of function that reconstructs the priority.

**Comment by zmthy** [comment]
What type would you expect the quality values to be?

**Comment by iand675** [comment]
Well, I don't need the actual quality values per se, but having an ordered list of MediaTypes grouped by priority seems like a sensible representation:

```
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
```
could be converted to:

``` haskell
contentTypes :: [[MediaType]]
contentTypes =
  [ [ ("text" // "html"), ("application" // "xhtml+xml"), ("application" // "xml") ]
  , [ ("image" // "webp"), ("image" // "apng"), ("*" // "*") ]
  ]
```
This way I could see which things are ties, and determine whether the match was specific or via wildcard match.

**Comment by zmthy** [comment]
I'm not opposed to just providing the quality values directly, and that would be a simpler interface than trying to order the values. The reason I haven't already exposed a way to access the value is that I'm not sure what an appropriate type is: internally they're stored as a number between 0 and 1000, since this is the real range of quality values available from the spec. I think this is would be an unexpected result to pull out of `Quality`, since the quality values are written as a value between 0 and 1.

A `QV` newtype that satisfies `Ord` but still doesn't expose the actual value would satisfy your use case, so maybe that's the right approach.

**Comment by iand675** [comment]
Yes, I think that would be fine. Ultimately quality values are only useful relative to each other, after all.
