### ISSUE TITLE
Property Test Failure

### ISSUE THREAD

**Issue by brainrape** [zmthy/http-media#27]
I got a test failure when building 0.7.1.2. Here's the relevant part of the output
```
Media:
  parseQuality:
    Without quality: [OK, passed 100 tests]
    With quality: [OK, passed 100 tests]
    With extensions: [OK, passed 100 tests]
  matchAccept:
    Highest quality: [OK, passed 100 tests]
    Most specific: [OK, passed 100 tests]
    Nothing: [OK, passed 100 tests]
    Never chooses q=0: [OK, passed 100 tests]
    Left biased: [OK, passed 100 tests]
    Against */*: [OK, passed 100 tests]
    Against type/*: [Failed]
*** Failed! Falsifiable (after 6 tests):
Just R/c;s=d;o=WyKaS;iH=m;I=ls;0=yf9qR /= Just R/C
(used seed 6662628523875800959)
```
It passed on the next run.

**Comment by zmthy** [comment]
Thanks for reporting the failure, this was a bug in the test. For this seed, two media types with the same main type and sub type appeared in the generated input, but only the one that appeared later in the list had parameters. This violated the assumption of the test that the lookup was guaranteed to be left biased, since specificity overrides direction.

I've pushed a fix, will merge soon.
