### ISSUE TITLE
Problem with `Accept` Parsing 

### ISSUE THREAD

**Issue by danclien** [zmthy/http-media#28]
We're using [`servant`](https://github.com/haskell-servant/servant), and we're running into two issue with a client sending us the following `Accept` header:

```
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
```

Both of these issues causes `servant` to return a 404, but I wanted to check to see if this should be fixed in `http-media` instead.

### Issue 1: Not parsing when the leading `0` is missing
`parseQuality` returns `Nothing` when the `q`-value doesn't have a leading `0`:

```
> parseQuality "*/*; q=0.2" :: Maybe [Quality MediaType]
Just [*/*;q=0.2]
> parseQuality "*/*; q=.2" :: Maybe [Quality MediaType]
Nothing
```

### Issue 2: Not parsing a single `*`
`parseAccept`/`parseQuality` returns `Nothing` when `*` is sent instead of `*/*`:

```
> parseQuality "*/*" :: Maybe [Quality MediaType]
Just [*/*;q=1]
> parseQuality "*/*; q=0.2" :: Maybe [Quality MediaType]
Just [*/*;q=0.2]
> parseQuality "*" :: Maybe [Quality MediaType]
Nothing
> parseAccept "*/*" :: Maybe MediaType
Just */*
> parseAccept "*" :: Maybe MediaType
Nothing
```

**Comment by zmthy** [comment]
Neither of these are valid uses of the Accept header syntax: quality values [must be preceded by either 0 or 1](https://tools.ietf.org/html/rfc7231#section-5.3.1) and media ranges in an Accept header [must have both a type and a subtype](https://tools.ietf.org/html/rfc7231#section-5.3.2). Servant should be returning a 400, since this is an ill-formed request.

**Comment by danclien** [comment]
Thanks for the references, @zmthy.
