### ISSUE TITLE
`matchAccept` doesn't properly process `*/*` (media-range with asterisks/stars/wildcards) when the `Accept` instance is `ByteString`

### ISSUE THREAD

**Issue by igrep** [zmthy/http-media#38]
# Minimum code to reproduce (and its result)

```haskell
-- lts-18.6 contains http-media-0.8.0.0:
$ stack --resolver=lts-18.6 exec --package=http-media --package=bytestring  ghci
> import Network.HTTP.Media
> import Data.ByteString (ByteString)
> :set -XOverloadedStrings
> matchAccept ["text/plain" :: ByteString] "*/*"
Nothing
> matchAccept ["text" // "plain"] "*/*"
Just text/plain
```

## Expected result

`matchAccept ["text/plain" :: ByteString] "*/*` should also return a `Just` as `matchAccept ["text" // "plain"] "*/*"` does.

**Comment by zmthy** [comment]
This is the expected behaviour: the `ByteString` instance of `Accept` is intended to work for headers where the matching logic is unknown, so we default to only matching case-insensitive values. This also doesn't work:

```haskell
matchAccept ["xyz" :: ByteString] "*"
```

If you want to apply matching rules that are specific to media types, the matching should be applied to values of `MediaType`, and if you have a `ByteString` instead, you can try to `parseAccept` first.

What's your use case that expects this to work like a media type match?

**Comment by igrep** [comment]
Yeah, later I found I should use `MediaType` instead actually in my use case, and I got sure of the reason of the behavior thanks to your reply.

Anyway, let me leave this issue here because I couldn't find it from the documents. I was confused because I mistook the type of `"text/html"` and `"application/json"` for `ByteString` when I saw the example for the first time:

```hs
getHeader >>= maybe send406Error sendResourceWith . mapAcceptMedia
    [ ("text/html",        asHtml)
    , ("application/json", asJson)
    ]
```

Thank you for the quick reply!
