### ISSUE TITLE
Inconsistent content matching in the presence of parameters

### ISSUE THREAD

**Issue by EggBaconAndSpam** [zmthy/http-media#42]
Does anyone have an idea what's going on here?

```
ghci> M.mapContentMedia [("text" M.// "plain" M./: ("charset","utf-8"), 1)] "text/plain"
Nothing

ghci> M.mapContentMedia [("text" M.// "plain" M./: ("charset","utf-8"), 1), ("text" M.// "plain", 2)] "text/plain"
Just 1
```

For context: servant's `PlainText` corresponds to `text/plain;charset=utf-8` and will _not_ accept `text/plain`. Upon adding a `Latin1` content type defined to handle both `text/plain` _and_ `text/plain;charset=iso-8859-1` servant suddenly tries to parse `text/plain` using `PlainText`.

**Comment by zmthy** [comment]
This is being caused by the way that the lookups currently identify a match in the keys of the pairs, then search through the list again for the matching key to return its mapped value. I think this works for Accept but not for Content-Type, but either way it's a bizarre way to implement it. I've tried reimplementing it by matching on the key while retaining the whole pair so we can return the mapped value directly afterwards and all the tests still seem to pass, so I don't think there was any reason to build it that way in the first place.

I'll put the new implementation together as a bugfix release after writing up some tests for it.
